# Generated by Django 4.1.6 on 2023-02-14 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_admin_manager_developer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(max_length=100)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("change_date", models.DateTimeField(auto_now=True)),
                ("deadline_date", models.DateTimeField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("nt", "new_task"),
                            ("id", "in_development"),
                            ("iq", "in_qa"),
                            ("ir", "in_code_review"),
                            ("rr", "ready_for_release"),
                            ("rd", "released"),
                            ("ar", "archived"),
                        ],
                        default="nt",
                        max_length=2,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("h", "high"), ("m", "medium"), ("l", "low")],
                        default="h",
                        max_length=1,
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        limit_choices_to={"is_stuff": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "tasks",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "u_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        max_length=30,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.task",
                    ),
                ),
            ],
        ),
    ]
