# Generated by Django 4.1.6 on 2023-02-15 11:46

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_task_tag"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Developer",
        ),
        migrations.AlterModelOptions(
            name="task",
            options={},
        ),
        migrations.RemoveField(
            model_name="tag",
            name="title",
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                default="low",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="state",
            field=models.CharField(
                choices=[
                    ("new_task", "New Task"),
                    ("in_development", "Id Development"),
                    ("in_qa", "In Qa"),
                    ("in_code_review", "In Code Review"),
                    ("ready_to_release", "Ready To Release"),
                    ("released", "Released"),
                    ("archived", "Archived"),
                ],
                default="new_task",
                max_length=255,
            ),
        ),
        migrations.RemoveField(
            model_name="task",
            name="title",
        ),
        migrations.CreateModel(
            name="Developer",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("main.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="tag",
            name="title",
            field=models.ManyToManyField(to="main.task"),
        ),
        migrations.AddField(
            model_name="task",
            name="title",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
