name: Main

on:
  pull_request:
    branches:
      - 'feature/django_app_api_coveralls'
  push:
    branches:
      - 'feature/django_app_api_coveralls'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Coveralls
        run: pip install coveralls
      - name: Run tests
        env:
          COVERAGE: true
          RAILS_ENV: test
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          docker-compose --file docker-compose.ci.yml run --rm api make test
      - name: Upload coverage data to Coveralls
        run: coveralls
        env:
          COVERAGE: true
          RAILS_ENV: test
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
