name: Coverage Status

on:
  pull_request:
    branches:
      - 'feature/django_app_api_coveralls'
  push:
    branches:
      - 'feature/django_app_api_coveralls'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      COVERAGE: true
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Coveralls
        run: pip install --upgrade coveralls
      - name: Run tests
        run: |
          docker-compose --file docker-compose.ci.yml run --rm api make test
          ls -la
          coveralls --file=TaskManager/coverage.lcov --service=github
        env:
          COVERAGE: true
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  coveralls:
    name: Indicate completion to coveralls.io
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --service=github --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
