name: Main

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        env:
          COVERAGE: true
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: docker-compose --file docker-compose.ci.yml run --rm api pytest
