name: Coverage Status

on:
  pull_request:
    branches:
      - 'feature/django_app_api_coveralls'
  push:
    branches:
      - 'feature/django_app_api_coveralls'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      COVERAGE: true
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Coveralls
        run: |
          pip3 install --upgrade coveralls
          pip3 install pyyml

      - name: Run tests
        run: |
          docker-compose --file docker-compose.ci.yml run --rm -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN api make test

  coveralls:
    name: Indicate completion to coveralls.io
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --service=github --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}